# .github/release.yml

changelog:
  categories:
    - title: Enchancements
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
