name: praisenter
title: Praisenter
summary: A presentation software package for churches
description: |
  Praisenter is a user-friendly presentation management tool designed to 
  streamline the creation and delivery of presentations tailored to churches. 
  With a focus on simplicity and functionality, Praisenter allows users to 
  create slides and templates with embedded images and videos with full 
  control of the content position, font size, colors, and more.  Templates 
  can be used to show Bible verses and song lyrics from the library.  Bibles 
  and song lyrics can be imported from a few source formats, but can also be 
  created from within the app.  Templates also support showing up to two 
  languages at the same time.  Praisenter supports presenting content on any 
  connected device whether it be a TV, projector, or monitor, limited only to 
  the number of connected devices.
adopt-info: metadata

grade: stable
confinement: strict
base: core22

# use lzo compression to speed up open time (makes the package larger though)
# https://snapcraft.io/docs/snapcraft-top-level-metadata
compression: lzo

apps:
  praisenter:
    # NOTE the command here  (used to be something like 
    # "desktop-launch $SNAP/..." which just didn't work
    # https://forum.snapcraft.io/t/missing-libraries-for-deb-using-core22-base/38436
    command: opt/praisenter/bin/Praisenter
    desktop: opt/praisenter/lib/praisenter-Praisenter.desktop
    # Add the gnome extension to provide for a large portion of the missing
    # libraries reported by snapcraft
    # https://forum.snapcraft.io/t/missing-libraries-for-deb-using-core22-base/38436
    # https://snapcraft.io/docs/supported-extensions
    extensions: [gnome]
    # I chose these based on the description of their purpose
    # https://snapcraft.io/docs/supported-interfaces
    plugs:
      - home
      - network
      - opengl
      - removable-media
      - unity7
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - audio-playback
      - hardware-observe

parts:
  praisenter:
    after: [lib]
    # The assumption is that the .deb file has been moved to the 
    # current directory of this yaml file and renamed so we don't
    # have to manually change any versioning
    source: ./praisenter.deb
    plugin: dump
    source-type: deb
    
  lib:
    plugin: nil
    # NOTE: these were the only missing libraries as reported by
    # snapcraft during build (there were other versions of them
    # missing, but I think you only need to stage the latest)

    # May need to switch to libavcodec60 when ubuntu-latest goes
    # to Ubuntu 23.x
    # https://stackoverflow.com/questions/77663867/error-creating-javafx-mediaplayer-using-mp3-on-ubuntu-23-10
    # https://bugs.openjdk.org/browse/JDK-8317508
    stage-packages:
    - libavcodec58
    - libavformat58

  metadata:
    # I'm using this to pull in the version only
    plugin: dump
    source: .
    # NOTE: this has to be *.metainfo.xml or *.appinfo.xml for whatever reason
    # https://github.com/snapcore/snapcraft/blob/ffbdabf53de21606d9d12e15f16d4bca5e4423a5/snapcraft/meta/appstream.py#L93
    parse-info: [praisenter.metainfo.xml]
