name: praisenter
version: '3.2.1'

source-code: https://github.com/praisenter/praisenter
issues: https://github.com/praisenter/praisenter/discussions
website: https://praisenter.org/
license: BSD-3-Clause
adopt-info: praisenter

icon: icon.svg
grade: stable
confinement: devmode # must be strict
base: core22

apps:
  praisenter:
    command: desktop-launch $SNAP/opt/praisenter/bin/Praisenter
    desktop: opt/praisenter/lib/praisenter-Praisenter.desktop
    plugs:
      - home
      - network
      - opengl
      - removable-media
      - unity7
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - audio-playback
      - hardware-observe

parts:
  praisenter:
    # The assumption is that the .deb file has been moved to the 
    # current directory of this yaml file and renamed so we don't
    # have to manually change any versioning
    source: ./praisenter.deb
    plugin: dump
    source-type: deb
    parse-info: [metainfo.xml]
    # override-build: |
    #   snapcraftctl build
      
    # #fix icon path
    # sed -i 's|Icon=iotacooler|Icon=${SNAP}/usr/share/pixmaps/iotacooler.png|g' $SNAPCRAFT_PART_INSTALL/usr/share/applications/iotacooler.desktop
    # stage-packages:
    #   - dbus
    # after: [desktop-qt5]

  # desktop-qt5: # custom define becasue no remote parts are supported when using a base (at least not on 16.04), https://github.com/ubuntu/snapcraft-desktop-helpers
  #   source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
  #   source-subdir: qt
  #   plugin: make
  #   make-parameters: ["FLAVOR=qt5"]
  #   build-packages:
  #     - qtbase5-dev
  #     - dpkg-dev
  #   stage-packages:
  #     - libxkbcommon0
  #     - ttf-ubuntu-font-family
  #     - dmz-cursor-theme
  #     - light-themes
  #     - adwaita-icon-theme
  #     - gnome-themes-standard
  #     - shared-mime-info
  #     - libqt5gui5
  #     - libgdk-pixbuf2.0-0
  #     - libqt5svg5 # for loading icon themes which are svg
  #     - try: [appmenu-qt5] # not available on core18
  #     - locales-all