#!/bin/bash

##################################################################
# The purpose of this script is to manually package a .pkg file for
# ad-hoc (manual) deployment.  This script relies on the app-image
# generated by jpackage, but does not use the .pkg packing offered
# by jpackage due to some specific requirements that Praisenter
# has.
# 
# The script consists of some high-level steps:
# 1. Copy in any additional dylib or executables into the app
#    bundle so that they can be loaded/run when deployed in the
#    MacOS sandbox
# 2. Copy in the appropriate provisioning profile to ensure
#    the app bundle can be validated and approved
# 3. Scan and sign all dylib and executable files inside the app
#    bundle
# 4. Scan and sign all dylib and executable files embedded in jar
#    files within the app bundle
# 5. Sign the whole app bundle
# 6. Package the app bundle into an app.pkg file
# 7. Package the app.pkg file into a new pkg file with installer
#    configuration like images, text, min-os versions, etc. and
#    sign the pkg
# 8. Notarize the installer pkg
# 9. Staple the installer pkg
##################################################################

APP_CERT="Developer ID Application: William Bittle (W9HCQKU68J)"
INST_CERT="Developer ID Installer: William Bittle (W9HCQKU68J)"

APP_ENTITLEMENTS="./packaging/macos64/app/entitlements.plist"
EMB_ENTITLEMENTS="./packaging/macos64/app/embed-entitlements.plist"
CONFIG_TEMPLATES="../packaging/macos64/app/config"

# change to the work directory
echo "Switching to target directory"
cd ../../../../target

TARGET_DIR=$(pwd)
echo "$TARGET_DIR"

WORK_DIR="$TARGET_DIR/pkg-work"
CONFIG_DIR="$WORK_DIR/config"
IMAGE_DIR="$WORK_DIR/image"
PACKAGES_DIR="$WORK_DIR/packages"
JAR_DIR="$WORK_DIR/jars"
IMAGE="Praisenter.app"

# make the work folders
echo "Creating working directories: $WORK_DIR"
mkdir -p "$IMAGE_DIR"
mkdir -p "$PACKAGES_DIR"

# copy the app-image to the image directory
echo "Copying app-image: $IMAGE to work directory: $IMAGE_DIR"
cp -R "./$IMAGE" "$IMAGE_DIR/$IMAGE"

echo "Copying config to work directory: $CONFIG_DIR"
cp -R "$CONFIG_TEMPLATES" "$WORK_DIR"

# copy the dylibs into the app dir
echo "Copying binaries to /app directory"
cp ../packaging/macos64/app/exec/libSecurityScopedBookmarkLibrary.dylib "$IMAGE_DIR/$IMAGE/Contents/app"
cp ../packaging/macos64/app/exec/ffmpeg "$IMAGE_DIR/$IMAGE/Contents/app"
cp ../packaging/macos64/app/exec/ffprobe "$IMAGE_DIR/$IMAGE/Contents/app"

# copy in the provisioning profile
echo "Copying provisioning profile"
cp ../packaging/macos64/app/content/DeveloperID.embedded.provisionprofile "$IMAGE_DIR/$IMAGE/Contents/embedded.provisionprofile"

# copy Assets.car
echo "Copying Assets.car"
cp ../packaging/macos64/app/resources/Assets.car "$IMAGE_DIR/$IMAGE/Contents/Resources/Assets.car"

# copy privacy manifest
echo "Copying privacy manifest"
cp ../packaging/macos64/app/content/PrivacyInfo.xcprivacy "$IMAGE_DIR/$IMAGE/Contents/Resources/PrivacyInfo.xcprivacy"

echo "Reading version number file"
VERSION_PLACEHOLDER="#VERSION#"
VERSION=$(head -n 1 ../release-version.txt)
echo "Replacing: '$VERSION_PLACEHOLDER' with version: '$VERSION'"

# update the Info.plist and .dist files with the latest version
echo "Update Info.plist and distribution.dlist with the latest version"
sed -i '' "s/$VERSION_PLACEHOLDER/$VERSION/g" "$IMAGE_DIR/$IMAGE/Contents/Info.plist"
sed -i '' "s/$VERSION_PLACEHOLDER/$VERSION/g" "$CONFIG_DIR/distribution.dist"

echo ""
echo "<------------------------------------------------->"
echo "Signing all contents of: $IMAGE"
find "$IMAGE_DIR/$IMAGE" -type f \( -perm +111 -o -name "*.dylib" -o -name "*.so" -o -name "ffmpeg" -o -name "ffprobe" \) | while read -r BINARY; do
    if [[ "$BINARY" != *"/Contents/MacOS/Praisenter"* ]]; then
        echo "Signing internal component: $BINARY"
        if [[ "$BINARY" = *".dylib" ]]; then
        	echo "Signing without entitlements"
            codesign -vvvv --options runtime --deep --force --timestamp --sign "$APP_CERT" "$BINARY"
        else
        	# only executables need entitlements added to the signature
        	echo "Signing with entitlements"
        	codesign -vvvv --options runtime --deep --force --timestamp --entitlements "$EMB_ENTITLEMENTS" --sign "$APP_CERT" "$BINARY"
        fi
    else
        echo "Skipping internal component: $BINARY"
    fi
done

echo ""
echo "<------------------------------------------------->"
echo "Signing jar embedded contents of: $IMAGE"
find "$IMAGE_DIR/$IMAGE/Contents/app" -type f \( -name "*.jar" \) | while read -r JAR; do
    # extract the jar contents
    name=$(basename "$JAR" .jar)
    tmp_dir="$JAR_DIR/$name"
    mkdir -p "$tmp_dir"
    jar xf "$JAR" -C "$tmp_dir"

    replace=$(find "$tmp_dir" -type f \( -perm +111 -o -name "*.dylib" -o -name "*.so" -o -name "ffmpeg" -o -name "ffprobe" \) | wc -c)
    # echo "$replace"

    find "$tmp_dir" -type f \( -perm +111 -o -name "*.dylib" -o -name "*.so" -o -name "ffmpeg" -o -name "ffprobe" \) | while read -r BINARY; do
        echo "Signing embedded component: $BINARY"
        #codesign -vvvv --options runtime --deep --force --timestamp --entitlements "$EMB_ENTITLEMENTS" --sign "$APP_CERT" "$BINARY"
        if [[ "$BINARY" = *".dylib" ]]; then
        	echo "Signing without entitlements"
            codesign -vvvv --options runtime --deep --force --timestamp --sign "$APP_CERT" "$BINARY"
        else
        	echo "Signing with entitlements"
        	# only executables need entitlements added to the signature
        	codesign -vvvv --options runtime --deep --force --timestamp --entitlements "$EMB_ENTITLEMENTS" --sign "$APP_CERT" "$BINARY"
        fi
    done
    
    if [[ $replace -gt 0 ]]; then
        echo "Replacing jar: $JAR"
        jar cf $JAR -C "$tmp_dir" .
    fi
done

echo ""
echo "<------------------------------------------------->"
echo "Signing app bundle" 
codesign -vvvv --options runtime --force --timestamp --entitlements "$APP_ENTITLEMENTS" --sign "$APP_CERT" "$IMAGE_DIR/$IMAGE"

echo ""
echo "<------------------------------------------------->"
echo "printing entitlements"
codesign -d --entitlements - "$IMAGE_DIR/$IMAGE"

echo ""
echo "<------------------------------------------------->"
echo "Run pkgbuild"
# pkgbuild -vv --root "$IMAGE_DIR" --install-location /Applications --component-plist "$CONFIG_DIR/cpl.plist" --identifier org.praisenter --sign "$INST_CERT" "$PACKAGES_DIR/Praisenter-app.pkg"
pkgbuild -vv --root "$IMAGE_DIR" --install-location /Applications --component-plist "$CONFIG_DIR/cpl.plist" --identifier org.praisenter "$PACKAGES_DIR/Praisenter-app.pkg" --version "$VERSION"

echo ""
echo "<------------------------------------------------->"
echo "Run productbuild"
# productbuild --resources "$CONFIG_DIR" --product "$CONFIG_DIR/product-def.plist" --distribution "$CONFIG_DIR/distribution.dist" --sign "$INST_CERT" --timestamp --package-path "$PACKAGES_DIR" ./Praisenter-signed.pkg
productbuild --resources "$CONFIG_DIR" --product "$CONFIG_DIR/product-def.plist" --distribution "$CONFIG_DIR/distribution.dist" --identifier org.praisenter --version "$VERSION" --sign "$INST_CERT" --timestamp --package-path "$PACKAGES_DIR" ./Praisenter-signed.pkg
# productbuild --resources "$CONFIG_DIR" --product "$CONFIG_DIR/product-def.plist" --sign "$INST_CERT" --component "$IMAGE_DIR/$IMAGE" /Applications ./Praisenter-unsigned.pkg

echo ""
echo "<------------------------------------------------->"
echo "Notarize package"
# run this once (find the password here: https://account.apple.com/account/manage/section/security)
# xcrun notarytool store-credentials "notary-profile-praisenter" --apple-id "USER_ID" --team-id "TEAM_ID" --password "****"
xcrun notarytool submit ./Praisenter-signed.pkg --keychain-profile "notary-profile-praisenter" --wait

echo ""
echo "<------------------------------------------------->"
echo "Staple the package" 
xcrun stapler staple ./Praisenter-signed.pkg

echo ""
echo "<------------------------------------------------->"
echo "Verify the pkg is install ready"
spctl --assess --type install -v ./Praisenter-signed.pkg

