CREATE TABLE BIBLES
(
   ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   DATA_SOURCE VARCHAR(100) NOT NULL,
   NAME VARCHAR(150) NOT NULL,
   LANGUAGE CHAR(3) NOT NULL,
   PRIMARY KEY (ID)
)

CREATE TABLE BIBLE_BOOKS
(
  BIBLE_ID INT NOT NULL,
  CODE VARCHAR(3) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  SEARCHABLE_NAME GENERATED ALWAYS AS (UCASE(NAME)),
  PRIMARY KEY(BIBLE_ID, CODE)
)
ALTER TABLE BIBLE_BOOKS ADD FOREIGN KEY (BIBLE_ID) REFERENCES BIBLES(ID)

CREATE TABLE BIBLE_VERSES
(
  ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  BIBLE_ID INT NOT NULL,
  BOOK_CODE VARCHAR(3) NOT NULL,
  CHAPTER INT NOT NULL,
  VERSE INT NOT NULL,
  SUB_VERSE INT,
  ORDER_BY INT,
  TEXT clob,
  SEARCHABLE_TEXT GENERATED ALWAYS AS (UCASE(TEXT)),
  PRIMARY KEY(BIBLE_ID, BOOK_CODE, CHAPTER, VERSE, SUB_VERSE)
)
ALTER TABLE BIBLE_VERSES ADD FOREIGN KEY (BIBLE_ID, BOOK_CODE) REFERENCES BIBLE_BOOKS(BIBLE_ID, CODE)

CREATE INDEX BO_A ON BIBLE_VERSES(BIBLE_ID,ORDER_BY)
CREATE INDEX BO_D ON BIBLE_VERSES(BIBLE_ID,ORDER_BY DESC)
CREATE INDEX BBCV ON BIBLE_VERSES(BIBLE_ID,BOOK_CODE,CHAPTER,VERSE)