CREATE TABLE ERRORS
(
   ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   JAVA_VERSION VARCHAR(150) NOT NULL,
   JAVA_VENDOR VARCHAR(150) NOT NULL,
   OS VARCHAR(150) NOT NULL,
   ARCHITECTURE VARCHAR(150) NOT NULL,
   MESSAGE CLOB,
   STACKTRACE CLOB,
   CONTACT VARCHAR(255),
   DESCRIPTION CLOB,
   ADDED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
   PRIMARY KEY (ID)
)
