name: Build All Pre-Release

on:
  #  push:
  #    branches: [ main ]
  #  pull_request:
  #    branches: [ main ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        include:
          # - os: ubuntu-latest
          #   branch: master
          # - os: windows-latest
          #   branch: master
          - os: macos-15-intel
            branch: macos
          # - os: macos-latest
          #   branch: macos
    runs-on: ${{ matrix.os }}
    steps:
      # Get latest from the current branch
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
        #   lfs: true

      # List git LFS files
      - name: Create Git LFS file list
        run: git lfs ls-files -l |cut -d' ' -f1 |sort >.git/lfs-hashes.txt

      # Restore LFS files from cache
      - name: Restore Git LFS object cache
        uses: actions/cache@v4
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfsdata-v1-${{ hashFiles('.git/lfs-hashes.txt') }}
          restore-keys: |
            ${{ runner.os }}-lfsdata-v1-
            ${{ runner.os }}-lfsdata

      # Check latest LFS files
      - name: Fetch any needed Git LFS objects and prune extraneous ones
        run: git lfs fetch --prune

      # Get latest LFS files
      - name: Check out Git LFS content
        run: git lfs checkout

      # This pulls the version number from the release-version.txt file
      - name: Read version
        id: readversion
        shell: pwsh
        run: |
          $content = Get-Content next-version.txt
          Write-Host "VERSION_NUMBER: $content"
          echo "VERSION_NUMBER=$content" >> $Env:GITHUB_ENV
          
      # Add MSBuild (WINDOWS)
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        if: runner.os == 'Windows'

      # Install FFmpeg (UBUNTU)
      - name: Install FFmpeg
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libavcodec-dev libavformat-dev

      # Install Wix 6 (WINDOWS)
      # https://github.com/petr-panteleyev/jpackage-gradle-plugin/issues/38#issuecomment-2873402088
      - name: Install WiX 6
        run: |
          dotnet tool install --global wix --version 6.0.2
          wix extension add -g WixToolset.Util.wixext/6.0.2
          wix extension add -g WixToolset.Ui.wixext/6.0.2
        if: runner.os == 'Windows'

      # Setup Java w/ JavaFX
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'zulu'
          java-package: jdk+fx
          cache: 'maven'
      
      # Run the Maven Build
      - name: "Build with Maven"
        run: mvn -B clean install --file pom.xml

      # Now attempt to build the msix (WINDOWS)
      - name: "Set appxmanifest version number"
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $filePath = "./packaging/windows64/msix/Praisenter/Package.appxmanifest"
          $xml = [xml](Get-Content -Path $filePath)
          $xml.Package.Identity.Name = "${{ secrets.MSIX_IDENTITY_NAME }}"
          $xml.Package.Identity.Publisher = "${{ secrets.MSIX_IDENTITY_PUBLISHER }}"
          $xml.Package.Identity.Version = "${{ env.VERSION_NUMBER }}.0"
          $xml.Save($filePath)

      # Copy all the build artifacts to the /App folder (WINDOWS)
      - name: "Copy msi to msix location"
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path "./packaging/windows64/msix/Praisenter/App"
          $copied = Copy-Item -Path "./target/installer-work/image/Praisenter/*" -Destination "./packaging/windows64/msix/Praisenter/App" -Recurse -PassThru
          $copied | ForEach-Object {
            Write-Host "Copied: '$($_.FullName)'"
          }

      # Build the msixupload file (WINDOWS)
      - name: Build MSIX package
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Push-Location -Path ./packaging/windows64/msix/Praisenter
          MSBuild.exe /nologo /restore /p:AppxBundle=Never /p:UapAppxPackageBuildMode=StoreUpload  /p:Configuration=Release /p:Platform=x64 /p:AppxPackageDir=..\..\..\..\target\ /p:AppxPackageSigningEnabled=false
          Pop-Location

      # Copy deb to snap folder (UBUNTU)
      - name: Copy deb to snap folder
        if: runner.os == 'Linux'
        shell: pwsh
        run: |
          $source = "./target/praisenter_${{ env.VERSION_NUMBER }}_amd64.deb"
          $target = "./packaging/linux64/snap/praisenter.deb"
          Copy-Item $source $target
          Write-Host "Copied: '$source' to '$target'"

      # Update metainfo.xml (UBUNTU)
      - name: Set metainfo.xml version number
        if: runner.os == 'Linux'
        shell: pwsh
        run: |
          $filePath = "./packaging/linux64/snap/praisenter.metainfo.xml"
          $date = Get-Date -Format "yyyy-MM-dd"
          $xml = [xml](Get-Content -Path $filePath)
          $xml.component.releases.release.version = "${{ env.VERSION_NUMBER }}"
          $xml.component.releases.release.date = "$date"
          $xml.Save($filePath)

      # # Install snapcraft (UBUNTU)
      # - name: Install Snapcraft
      #   uses: samuelmeuli/action-snapcraft@v2
      - name: Build snap file
        if: runner.os == 'Linux'
        id: snapcraft
        uses: snapcore/action-build@v1
        with:
          path: ./packaging/linux64/snap/

      # Copy snap to target folder (UBUNTU)
      - name: Copy snap to target folder
        if: runner.os == 'Linux'
        shell: pwsh
        run: |
          $source = "${{ steps.snapcraft.outputs.snap }}"
          $target = "./target/praisenter_${{ env.VERSION_NUMBER }}_amd64.snap"
          Copy-Item $source $target
          Write-Host "Copied: '$source' to '$target'"

      # Setup for macos signing (MACOS)
      - name: Install the Apple certificate and provisioning profile
        if: runner.os == 'macOS'
        env:
          PKG_DEVELOPER_ID_APPLICATION_CERTIFICATE_BASE64: ${{ secrets.PKG_DEVELOPER_ID_APPLICATION_CERTIFICATE_BASE64 }}
          PKG_DEVELOPER_ID_INSTALLER_CERTIFICATE_BASE64: ${{ secrets.PKG_DEVELOPER_ID_INSTALLER_CERTIFICATE_BASE64 }}
          PKG_MAC_DEVELOPER_APPLICATION_CERTIFICATE_BASE64: ${{ secrets.PKG_MAC_DEVELOPER_APPLICATION_CERTIFICATE_BASE64 }}
          PKG_MAC_DEVELOPER_INSTALLER_CERTIFICATE_BASE64: ${{ secrets.PKG_MAC_DEVELOPER_INSTALLER_CERTIFICATE_BASE64 }}
          PKG_CERTIFICATE_PASSWORD: ${{ secrets.PKG_CERTIFICATE_PASSWORD }}
          PKG_ADHOC_PROVISION_PROFILE_BASE64: ${{ secrets.PKG_ADHOC_PROVISION_PROFILE_BASE64 }}
          PKG_STORE_PROVISION_PROFILE_BASE64: ${{ secrets.PKG_STORE_PROVISION_PROFILE_BASE64 }}
          PKG_KEYCHAIN_PASSWORD: ${{ secrets.PKG_KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          DEVELOPER_ID_APPLICATION_CERT_PATH=$RUNNER_TEMP/developer_id_application.p12
          DEVELOPER_ID_INSTALLER_CERT_PATH=$RUNNER_TEMP/developer_id_installer.p12
          MAC_DEVELOPER_APPLICATION_CERT_PATH=$RUNNER_TEMP/mac_developer_application.p12
          MAC_DEVELOPER_INSTALLER_CERT_PATH=$RUNNER_TEMP/mac_developer_installer.p12
          ADHOC_PROVISION_PROFILE_PATH=$RUNNER_TEMP/adhoc/embedded.mobileprovision
          STORE_PROVISION_PROFILE_PATH=$RUNNER_TEMP/store/embedded.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$PKG_DEVELOPER_ID_APPLICATION_CERTIFICATE_BASE64" | base64 --decode -o $DEVELOPER_ID_APPLICATION_CERT_PATH
          echo -n "$PKG_DEVELOPER_ID_INSTALLER_CERTIFICATE_BASE64" | base64 --decode -o $DEVELOPER_ID_INSTALLER_CERT_PATH
          echo -n "$PKG_MAC_DEVELOPER_APPLICATION_CERTIFICATE_BASE64" | base64 --decode -o $MAC_DEVELOPER_APPLICATION_CERT_PATH
          echo -n "$PKG_MAC_DEVELOPER_INSTALLER_CERTIFICATE_BASE64" | base64 --decode -o $MAC_DEVELOPER_INSTALLER_CERT_PATH
          echo -n "$PKG_ADHOC_PROVISION_PROFILE_BASE64" | base64 --decode -o $ADHOC_PROVISION_PROFILE_PATH
          echo -n "$PKG_STORE_PROVISION_PROFILE_BASE64" | base64 --decode -o $STORE_PROVISION_PROFILE_PATH

          # create temporary keychain
          security create-keychain -p "$PKG_KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$PKG_KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificates to keychain
          security import $DEVELOPER_ID_APPLICATION_CERT_PATH -P "$PKG_CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security import $DEVELOPER_ID_INSTALLER_CERT_PATH -P "$PKG_CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security import $MAC_DEVELOPER_APPLICATION_CERT_PATH -P "$PKG_CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security import $MAC_DEVELOPER_INSTALLER_CERT_PATH -P "$PKG_CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security set-key-partition-list -S apple-tool:,apple: -k "$PKG_KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

      # Package and sign for for the MacOS store
      - name: Package and sign for MacOS store
        if: runner.os == 'macOS'
        run: |
          APP_CERT="3rd Party Mac Developer Application: William Bittle (W9HCQKU68J)"
          INST_CERT="3rd Party Mac Developer Installer: William Bittle (W9HCQKU68J)"
          ARCH=$(echo "$RUNNER_ARCH" | tr '[:upper:]' '[:lower:]')

          APP_ENTITLEMENTS="./packaging/macos64/app/entitlements.plist"
          EMB_ENTITLEMENTS="./packaging/macos64/app/embed-entitlements.plist"
          CONFIG_TEMPLATES="../packaging/macos64/app/config"

          # change to the work directory
          echo "Switching to target directory"
          cd ./target

          TARGET_DIR=$(pwd)
          echo "$TARGET_DIR"

          WORK_DIR="$TARGET_DIR/pkg-work"
          CONFIG_DIR="$WORK_DIR/config"
          IMAGE_DIR="$WORK_DIR/image"
          PACKAGES_DIR="$WORK_DIR/packages"
          JAR_DIR="$WORK_DIR/jars"
          IMAGE="Praisenter.app"

          # make the work folders
          echo "Creating working directories: $WORK_DIR"
          mkdir -p "$IMAGE_DIR"
          mkdir -p "$PACKAGES_DIR"

          # copy the app-image to the image directory
          echo "Copying app-image: $IMAGE to work directory: $IMAGE_DIR"
          cp -R "./$IMAGE" "$IMAGE_DIR/$IMAGE"

          echo "Copying config to work directory: $CONFIG_DIR"
          cp -R "$CONFIG_TEMPLATES" "$WORK_DIR"

          # copy the dylibs into the app dir
          echo "Copying binaries to /app directory"
          cp ../packaging/macos64/app/exec/libSecurityScopedBookmarkLibrary.dylib "$IMAGE_DIR/$IMAGE/Contents/app"
          cp ../packaging/macos64/app/exec/ffmpeg "$IMAGE_DIR/$IMAGE/Contents/app"
          cp ../packaging/macos64/app/exec/ffprobe "$IMAGE_DIR/$IMAGE/Contents/app"

          # copy in the provisioning profile
          echo "Copying provisioning profile"
          cp "$RUNNER_TEMP/store/embedded.mobileprovision" "$IMAGE_DIR/$IMAGE/Contents/embedded.provisionprofile"

          # copy Assets.car
          echo "Copying Assets.car"
          cp ../packaging/macos64/app/resources/Assets.car "$IMAGE_DIR/$IMAGE/Contents/Resources/Assets.car"

          # copy privacy manifest
          echo "Copying privacy manifest"
          cp ../packaging/macos64/app/content/PrivacyInfo.xcprivacy "$IMAGE_DIR/$IMAGE/Contents/Resources/PrivacyInfo.xcprivacy"

          echo "Reading version number file"
          VERSION_PLACEHOLDER="#VERSION#"
          VERSION="${{ env.VERSION_NUMBER }}"
          echo "Replacing: '$VERSION_PLACEHOLDER' with version: '$VERSION'"

          # update the Info.plist and .dist files with the latest version
          echo "Update Info.plist and distribution.dlist with the latest version"
          sed -i '' "s/$VERSION_PLACEHOLDER/$VERSION/g" "$IMAGE_DIR/$IMAGE/Contents/Info.plist"
          sed -i '' "s/$VERSION_PLACEHOLDER/$VERSION/g" "$CONFIG_DIR/distribution.dist"

          echo ""
          echo "<------------------------------------------------->"
          echo "Signing all contents of: $IMAGE"
          find "$IMAGE_DIR/$IMAGE" -type f \( -perm +111 -o -name "*.dylib" -o -name "*.so" -o -name "ffmpeg" -o -name "ffprobe" \) | while read -r BINARY; do
              if [[ "$BINARY" != *"/Contents/MacOS/Praisenter"* ]]; then
                  echo "Signing internal component: $BINARY"
                  if [[ "$BINARY" = *".dylib" ]]; then
                    echo "Signing without entitlements"
                      codesign -vvvv --options runtime --deep --force --timestamp --sign "$APP_CERT" "$BINARY"
                  else
                    # only executables need entitlements added to the signature
                    echo "Signing with entitlements"
                    codesign -vvvv --options runtime --deep --force --timestamp --entitlements "$EMB_ENTITLEMENTS" --sign "$APP_CERT" "$BINARY"
                  fi
              else
                  echo "Skipping internal component: $BINARY"
              fi
          done

          echo ""
          echo "<------------------------------------------------->"
          echo "Signing jar embedded contents of: $IMAGE"
          find "$IMAGE_DIR/$IMAGE/Contents/app" -type f \( -name "*.jar" \) | while read -r JAR; do
              # extract the jar contents
              name=$(basename "$JAR" .jar)
              tmp_dir="$JAR_DIR/$name"
              mkdir -p "$tmp_dir"
              jar xf "$JAR" -C "$tmp_dir"

              replace=$(find "$tmp_dir" -type f \( -perm +111 -o -name "*.dylib" -o -name "*.so" -o -name "ffmpeg" -o -name "ffprobe" \) | wc -c)
              # echo "$replace"

              find "$tmp_dir" -type f \( -perm +111 -o -name "*.dylib" -o -name "*.so" -o -name "ffmpeg" -o -name "ffprobe" \) | while read -r BINARY; do
                  echo "Signing embedded component: $BINARY"
                  #codesign -vvvv --options runtime --deep --force --timestamp --entitlements "$EMB_ENTITLEMENTS" --sign "$APP_CERT" "$BINARY"
                  if [[ "$BINARY" = *".dylib" ]]; then
                    echo "Signing without entitlements"
                      codesign -vvvv --options runtime --deep --force --timestamp --sign "$APP_CERT" "$BINARY"
                  else
                    echo "Signing with entitlements"
                    # only executables need entitlements added to the signature
                    codesign -vvvv --options runtime --deep --force --timestamp --entitlements "$EMB_ENTITLEMENTS" --sign "$APP_CERT" "$BINARY"
                  fi
              done
              
              if [[ $replace -gt 0 ]]; then
                  echo "Replacing jar: $JAR"
                  jar cf $JAR -C "$tmp_dir" .
              fi
          done

          echo ""
          echo "<------------------------------------------------->"
          echo "Signing app bundle" 
          codesign -vvvv --options runtime --force --timestamp --entitlements "$APP_ENTITLEMENTS" --sign "$APP_CERT" "$IMAGE_DIR/$IMAGE"

          echo ""
          echo "<------------------------------------------------->"
          echo "printing entitlements"
          codesign -d --entitlements - "$IMAGE_DIR/$IMAGE"

          echo ""
          echo "<------------------------------------------------->"
          echo "Run pkgbuild"
          pkgbuild -vv --root "$IMAGE_DIR" --install-location /Applications --component-plist "$CONFIG_DIR/cpl.plist" --identifier org.praisenter "$PACKAGES_DIR/Praisenter-app.pkg" --version "$VERSION"

          echo ""
          echo "<------------------------------------------------->"
          echo "Run productbuild"
          productbuild --resources "$CONFIG_DIR" --product "$CONFIG_DIR/product-def.plist" --distribution "$CONFIG_DIR/distribution.dist" --identifier org.praisenter --version "$VERSION" --sign "$INST_CERT" --timestamp --package-path "$PACKAGES_DIR" ./Praisenter_${{ env.VERSION_NUMBER }}_$ARCH_store.pkg

      # Package and sign for for MacOS adhoc deployment
      - name: Package and sign for MacOS adhoc deployment
        if: runner.os == 'macOS'
        run: |
          APP_CERT="Developer ID Application: William Bittle (W9HCQKU68J)"
          INST_CERT="Developer ID Installer: William Bittle (W9HCQKU68J)"
          ARCH=$(echo "$RUNNER_ARCH" | tr '[:upper:]' '[:lower:]')

          APP_ENTITLEMENTS="./packaging/macos64/app/entitlements.plist"
          EMB_ENTITLEMENTS="./packaging/macos64/app/embed-entitlements.plist"
          CONFIG_TEMPLATES="../packaging/macos64/app/config"

          # change to the work directory
          echo "Switching to target directory"
          cd ./target

          TARGET_DIR=$(pwd)
          echo "$TARGET_DIR"

          WORK_DIR="$TARGET_DIR/pkg-work"
          CONFIG_DIR="$WORK_DIR/config"
          IMAGE_DIR="$WORK_DIR/image"
          PACKAGES_DIR="$WORK_DIR/packages"
          JAR_DIR="$WORK_DIR/jars"
          IMAGE="Praisenter.app"

          # make the work folders
          echo "Creating working directories: $WORK_DIR"
          mkdir -p "$IMAGE_DIR"
          mkdir -p "$PACKAGES_DIR"

          # copy the app-image to the image directory
          echo "Copying app-image: $IMAGE to work directory: $IMAGE_DIR"
          cp -R "./$IMAGE" "$IMAGE_DIR/$IMAGE"

          echo "Copying config to work directory: $CONFIG_DIR"
          cp -R "$CONFIG_TEMPLATES" "$WORK_DIR"

          # copy the dylibs into the app dir
          echo "Copying binaries to /app directory"
          cp ../packaging/macos64/app/exec/libSecurityScopedBookmarkLibrary.dylib "$IMAGE_DIR/$IMAGE/Contents/app"
          cp ../packaging/macos64/app/exec/ffmpeg "$IMAGE_DIR/$IMAGE/Contents/app"
          cp ../packaging/macos64/app/exec/ffprobe "$IMAGE_DIR/$IMAGE/Contents/app"

          # copy in the provisioning profile
          echo "Copying provisioning profile"
          cp "$RUNNER_TEMP/adhoc/embedded.mobileprovision" "$IMAGE_DIR/$IMAGE/Contents/embedded.provisionprofile"

          # copy Assets.car
          echo "Copying Assets.car"
          cp ../packaging/macos64/app/resources/Assets.car "$IMAGE_DIR/$IMAGE/Contents/Resources/Assets.car"

          # copy privacy manifest
          echo "Copying privacy manifest"
          cp ../packaging/macos64/app/content/PrivacyInfo.xcprivacy "$IMAGE_DIR/$IMAGE/Contents/Resources/PrivacyInfo.xcprivacy"

          echo "Reading version number file"
          VERSION_PLACEHOLDER="#VERSION#"
          VERSION="${{ env.VERSION_NUMBER }}"
          echo "Replacing: '$VERSION_PLACEHOLDER' with version: '$VERSION'"

          # update the Info.plist and .dist files with the latest version
          echo "Update Info.plist and distribution.dlist with the latest version"
          sed -i '' "s/$VERSION_PLACEHOLDER/$VERSION/g" "$IMAGE_DIR/$IMAGE/Contents/Info.plist"
          sed -i '' "s/$VERSION_PLACEHOLDER/$VERSION/g" "$CONFIG_DIR/distribution.dist"

          echo ""
          echo "<------------------------------------------------->"
          echo "Signing all contents of: $IMAGE"
          find "$IMAGE_DIR/$IMAGE" -type f \( -perm +111 -o -name "*.dylib" -o -name "*.so" -o -name "ffmpeg" -o -name "ffprobe" \) | while read -r BINARY; do
              if [[ "$BINARY" != *"/Contents/MacOS/Praisenter"* ]]; then
                  echo "Signing internal component: $BINARY"
                  if [[ "$BINARY" = *".dylib" ]]; then
                    echo "Signing without entitlements"
                      codesign -vvvv --options runtime --deep --force --timestamp --sign "$APP_CERT" "$BINARY"
                  else
                    # only executables need entitlements added to the signature
                    echo "Signing with entitlements"
                    codesign -vvvv --options runtime --deep --force --timestamp --entitlements "$EMB_ENTITLEMENTS" --sign "$APP_CERT" "$BINARY"
                  fi
              else
                  echo "Skipping internal component: $BINARY"
              fi
          done

          echo ""
          echo "<------------------------------------------------->"
          echo "Signing jar embedded contents of: $IMAGE"
          find "$IMAGE_DIR/$IMAGE/Contents/app" -type f \( -name "*.jar" \) | while read -r JAR; do
              # extract the jar contents
              name=$(basename "$JAR" .jar)
              tmp_dir="$JAR_DIR/$name"
              mkdir -p "$tmp_dir"
              jar xf "$JAR" -C "$tmp_dir"

              replace=$(find "$tmp_dir" -type f \( -perm +111 -o -name "*.dylib" -o -name "*.so" -o -name "ffmpeg" -o -name "ffprobe" \) | wc -c)
              # echo "$replace"

              find "$tmp_dir" -type f \( -perm +111 -o -name "*.dylib" -o -name "*.so" -o -name "ffmpeg" -o -name "ffprobe" \) | while read -r BINARY; do
                  echo "Signing embedded component: $BINARY"
                  #codesign -vvvv --options runtime --deep --force --timestamp --entitlements "$EMB_ENTITLEMENTS" --sign "$APP_CERT" "$BINARY"
                  if [[ "$BINARY" = *".dylib" ]]; then
                    echo "Signing without entitlements"
                      codesign -vvvv --options runtime --deep --force --timestamp --sign "$APP_CERT" "$BINARY"
                  else
                    echo "Signing with entitlements"
                    # only executables need entitlements added to the signature
                    codesign -vvvv --options runtime --deep --force --timestamp --entitlements "$EMB_ENTITLEMENTS" --sign "$APP_CERT" "$BINARY"
                  fi
              done
              
              if [[ $replace -gt 0 ]]; then
                  echo "Replacing jar: $JAR"
                  jar cf $JAR -C "$tmp_dir" .
              fi
          done

          echo ""
          echo "<------------------------------------------------->"
          echo "Signing app bundle" 
          codesign -vvvv --options runtime --force --timestamp --entitlements "$APP_ENTITLEMENTS" --sign "$APP_CERT" "$IMAGE_DIR/$IMAGE"

          echo ""
          echo "<------------------------------------------------->"
          echo "printing entitlements"
          codesign -d --entitlements - "$IMAGE_DIR/$IMAGE"

          echo ""
          echo "<------------------------------------------------->"
          echo "Run pkgbuild"
          pkgbuild -vv --root "$IMAGE_DIR" --install-location /Applications --component-plist "$CONFIG_DIR/cpl.plist" --identifier org.praisenter "$PACKAGES_DIR/Praisenter-app.pkg" --version "$VERSION"

          echo ""
          echo "<------------------------------------------------->"
          echo "Run productbuild"
          productbuild --resources "$CONFIG_DIR" --product "$CONFIG_DIR/product-def.plist" --distribution "$CONFIG_DIR/distribution.dist" --identifier org.praisenter --version "$VERSION" --sign "$INST_CERT" --timestamp --package-path "$PACKAGES_DIR" ./Praisenter_${{ env.VERSION_NUMBER }}_$ARCH_adhoc.pkg

          # echo ""
          # echo "<------------------------------------------------->"
          # echo "Notarize package"
          # # run this once (find the password here: https://account.apple.com/account/manage/section/security)
          # # xcrun notarytool store-credentials "notary-profile-praisenter" --apple-id "USER_ID" --team-id "TEAM_ID" --password "****"
          # xcrun notarytool submit ./Praisenter-signed.pkg --keychain-profile "notary-profile-praisenter" --wait

          # echo ""
          # echo "<------------------------------------------------->"
          # echo "Staple the package" 
          # xcrun stapler staple ./Praisenter-signed.pkg

          # echo ""
          # echo "<------------------------------------------------->"
          # echo "Verify the pkg is install ready"
          # spctl --assess --type install -v ./Praisenter-signed.pkg

      # Publish the artifacts
      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          retention-days: 1
          path: |
            ./target/*.msi
            ./target/*.msixupload
            ./target/*.deb
            ./target/*.snap
            ./target/*.app

  github-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Get latest from the current branch
      - uses: actions/checkout@v2

      # This pulls the version number from the release-version.txt file
      - name: Read version
        id: readversion
        shell: pwsh
        run: |
          $content = Get-Content release-version.txt
          Write-Host "VERSION_NUMBER: $content"
          echo "VERSION_NUMBER=$content" >> $Env:GITHUB_ENV

      # Download all artifacts
      - name: Download artifacts
        uses: actions/download-artifact@v4

      # Create one release called 3.2.1 (for example)
      - name: Create Versioned Pre-Release
        uses: softprops/action-gh-release@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN}}"
          name: Praisenter v${{ env.VERSION_NUMBER }}.prerelease
          tag_name: ${{ env.VERSION_NUMBER }}.prerelease
          prerelease: false
          generate_release_notes: true
          make_latest: true
          files: | 
            ./dist-windows-latest/*.msi
            ./dist-windows-latest/*.msixupload
            ./dist-ubuntu-latest/*.deb
            ./dist-ubuntu-latest/*.snap
            ./dist-macos-15-intel/*.app
            ./dist-macos-latest/*.app

#      # Now pull the latest release body
#      - name: Read release notes
#        id: release
#        uses: cardinalby/git-get-release-action@v1
#        env:
#          GITHUB_TOKEN: ${{ github.token }}
#        with:
#          tag: ${{ env.VERSION_NUMBER }}
#
#      # Now update the versioned release with the same body
#      - name: Copy release notes
#        uses: meeDamian/github-release@2.0
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          tag: ${{ env.VERSION_NUMBER }}
#          body: ${{ steps.release.outputs.body }}
#          allow_override: true

  # store-deploy:
  #   needs: github-release
  #   runs-on: ubuntu-latest
  #   steps:
  #     # Get latest from the current branch
  #     - uses: actions/checkout@v2

  #     # This pulls the version number from the release-version.txt file
  #     - name: Read version
  #       id: readversion
  #       shell: pwsh
  #       run: |
  #         $content = Get-Content release-version.txt
  #         Write-Host "VERSION_NUMBER: $content"
  #         echo "VERSION_NUMBER=$content" >> $Env:GITHUB_ENV

  #     # Download all artifacts
  #     - name: Download artifacts
  #       uses: actions/download-artifact@v4

  #     # now push to the stores