name: Build All Pre-Release

on:
  #  push:
  #    branches: [ main ]
  #  pull_request:
  #    branches: [ main ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        include:
          # - os: ubuntu-latest
          #   branch: master
          # - os: windows-latest
          #   branch: master
          - os: macos-15-intel
            branch: macos
            arch: x64
          # - os: macos-latest
          #   branch: macos
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: nschloe/action-cached-lfs-checkout@v1
        with:
          ref: ${{ matrix.branch }}

      # # Get latest from the current branch
      # - uses: actions/checkout@v4
      #   with:
      #     ref: ${{ matrix.branch }}
      #   #   lfs: true

      # # List git LFS files
      # - name: Create Git LFS file list
      #   run: git lfs ls-files -l |cut -d' ' -f1 |sort >.git/lfs-hashes.txt

      # # Restore LFS files from cache
      # - name: Restore Git LFS object cache
      #   uses: actions/cache@v4
      #   with:
      #     path: .git/lfs
      #     key: ${{ runner.os }}-lfsdata-v1-${{ hashFiles('.git/lfs-hashes.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-lfsdata-v1-
      #       ${{ runner.os }}-lfsdata

      # # Check latest LFS files
      # - name: Fetch any needed Git LFS objects and prune extraneous ones
      #   run: git lfs fetch --prune

      # # Get latest LFS files
      # - name: Check out Git LFS content
      #   run: git lfs checkout

      # This pulls the version number from the release-version.txt file
      - name: Read version
        id: readversion
        shell: pwsh
        run: |
          $content = Get-Content next-version.txt
          Write-Host "VERSION_NUMBER: $content"
          echo "VERSION_NUMBER=$content" >> $Env:GITHUB_ENV
          
      # Add MSBuild (WINDOWS)
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        if: runner.os == 'Windows'

      # Install FFmpeg (UBUNTU)
      - name: Install FFmpeg
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libavcodec-dev libavformat-dev

      # Install Wix 6 (WINDOWS)
      # https://github.com/petr-panteleyev/jpackage-gradle-plugin/issues/38#issuecomment-2873402088
      - name: Install WiX 6
        run: |
          dotnet tool install --global wix --version 6.0.2
          wix extension add -g WixToolset.Util.wixext/6.0.2
          wix extension add -g WixToolset.Ui.wixext/6.0.2
        if: runner.os == 'Windows'

      # Setup Java w/ JavaFX
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'zulu'
          java-package: jdk+fx
          cache: 'maven'
      
      # Run the Maven Build
      - name: "Build with Maven"
        run: mvn -B clean install --file pom.xml

      # Now attempt to build the msix (WINDOWS)
      - name: "Set appxmanifest version number"
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $filePath = "./packaging/windows64/msix/Praisenter/Package.appxmanifest"
          $xml = [xml](Get-Content -Path $filePath)
          $xml.Package.Identity.Name = "${{ secrets.MSIX_IDENTITY_NAME }}"
          $xml.Package.Identity.Publisher = "${{ secrets.MSIX_IDENTITY_PUBLISHER }}"
          $xml.Package.Identity.Version = "${{ env.VERSION_NUMBER }}.0"
          $xml.Save($filePath)

      # Copy all the build artifacts to the /App folder (WINDOWS)
      - name: "Copy msi to msix location"
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path "./packaging/windows64/msix/Praisenter/App"
          $copied = Copy-Item -Path "./target/installer-work/image/Praisenter/*" -Destination "./packaging/windows64/msix/Praisenter/App" -Recurse -PassThru
          $copied | ForEach-Object {
            Write-Host "Copied: '$($_.FullName)'"
          }

      # Build the msixupload file (WINDOWS)
      - name: Build MSIX package
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Push-Location -Path ./packaging/windows64/msix/Praisenter
          MSBuild.exe /nologo /restore /p:AppxBundle=Never /p:UapAppxPackageBuildMode=StoreUpload  /p:Configuration=Release /p:Platform=x64 /p:AppxPackageDir=..\..\..\..\target\ /p:AppxPackageSigningEnabled=false
          Pop-Location

      # Copy deb to snap folder (UBUNTU)
      - name: Copy deb to snap folder
        if: runner.os == 'Linux'
        shell: pwsh
        run: |
          $source = "./target/praisenter_${{ env.VERSION_NUMBER }}_amd64.deb"
          $target = "./packaging/linux64/snap/praisenter.deb"
          Copy-Item $source $target
          Write-Host "Copied: '$source' to '$target'"

      # Update metainfo.xml (UBUNTU)
      - name: Set metainfo.xml version number
        if: runner.os == 'Linux'
        shell: pwsh
        run: |
          $filePath = "./packaging/linux64/snap/praisenter.metainfo.xml"
          $date = Get-Date -Format "yyyy-MM-dd"
          $xml = [xml](Get-Content -Path $filePath)
          $xml.component.releases.release.version = "${{ env.VERSION_NUMBER }}"
          $xml.component.releases.release.date = "$date"
          $xml.Save($filePath)

      # # Install snapcraft (UBUNTU)
      # - name: Install Snapcraft
      #   uses: samuelmeuli/action-snapcraft@v2
      - name: Build snap file
        if: runner.os == 'Linux'
        id: snapcraft
        uses: snapcore/action-build@v1
        with:
          path: ./packaging/linux64/snap/

      # Copy snap to target folder (UBUNTU)
      - name: Copy snap to target folder
        if: runner.os == 'Linux'
        shell: pwsh
        run: |
          $source = "${{ steps.snapcraft.outputs.snap }}"
          $target = "./target/praisenter_${{ env.VERSION_NUMBER }}_amd64.snap"
          Copy-Item $source $target
          Write-Host "Copied: '$source' to '$target'"

      # Setup for macos signing (MACOS)
      - name: Install the Apple certificate and provisioning profile
        if: runner.os == 'macOS'
        env:
          PKG_DEVELOPER_ID_APPLICATION_CERTIFICATE_BASE64: ${{ secrets.PKG_DEVELOPER_ID_APPLICATION_CERTIFICATE_BASE64 }}
          PKG_DEVELOPER_ID_INSTALLER_CERTIFICATE_BASE64: ${{ secrets.PKG_DEVELOPER_ID_INSTALLER_CERTIFICATE_BASE64 }}
          PKG_MAC_DEVELOPER_APPLICATION_CERTIFICATE_BASE64: ${{ secrets.PKG_MAC_DEVELOPER_APPLICATION_CERTIFICATE_BASE64 }}
          PKG_MAC_DEVELOPER_INSTALLER_CERTIFICATE_BASE64: ${{ secrets.PKG_MAC_DEVELOPER_INSTALLER_CERTIFICATE_BASE64 }}
          PKG_CERTIFICATE_PASSWORD: ${{ secrets.PKG_CERTIFICATE_PASSWORD }}
          PKG_ADHOC_PROVISION_PROFILE_BASE64: ${{ secrets.PKG_ADHOC_PROVISION_PROFILE_BASE64 }}
          PKG_STORE_PROVISION_PROFILE_BASE64: ${{ secrets.PKG_STORE_PROVISION_PROFILE_BASE64 }}
          PKG_KEYCHAIN_PASSWORD: ${{ secrets.PKG_KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          DEVELOPER_ID_APPLICATION_CERT_PATH=$RUNNER_TEMP/developer_id_application.p12
          DEVELOPER_ID_INSTALLER_CERT_PATH=$RUNNER_TEMP/developer_id_installer.p12
          MAC_DEVELOPER_APPLICATION_CERT_PATH=$RUNNER_TEMP/mac_developer_application.p12
          MAC_DEVELOPER_INSTALLER_CERT_PATH=$RUNNER_TEMP/mac_developer_installer.p12
          ADHOC_PROVISION_PROFILE_PATH=$RUNNER_TEMP/adhoc/embedded.mobileprovision
          STORE_PROVISION_PROFILE_PATH=$RUNNER_TEMP/store/embedded.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          mkdir -p $RUNNER_TEMP/adhoc
          mkdir -p $RUNNER_TEMP/store

          # import certificate and provisioning profile from secrets
          echo -n "$PKG_DEVELOPER_ID_APPLICATION_CERTIFICATE_BASE64" | base64 --decode -o $DEVELOPER_ID_APPLICATION_CERT_PATH
          echo -n "$PKG_DEVELOPER_ID_INSTALLER_CERTIFICATE_BASE64" | base64 --decode -o $DEVELOPER_ID_INSTALLER_CERT_PATH
          echo -n "$PKG_MAC_DEVELOPER_APPLICATION_CERTIFICATE_BASE64" | base64 --decode -o $MAC_DEVELOPER_APPLICATION_CERT_PATH
          echo -n "$PKG_MAC_DEVELOPER_INSTALLER_CERTIFICATE_BASE64" | base64 --decode -o $MAC_DEVELOPER_INSTALLER_CERT_PATH
          echo -n "$PKG_ADHOC_PROVISION_PROFILE_BASE64" | base64 --decode -o $ADHOC_PROVISION_PROFILE_PATH
          echo -n "$PKG_STORE_PROVISION_PROFILE_BASE64" | base64 --decode -o $STORE_PROVISION_PROFILE_PATH

          # create temporary keychain
          security create-keychain -p "$PKG_KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$PKG_KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificates to keychain
          security import $DEVELOPER_ID_APPLICATION_CERT_PATH -P "$PKG_CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security import $DEVELOPER_ID_INSTALLER_CERT_PATH -P "$PKG_CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security import $MAC_DEVELOPER_APPLICATION_CERT_PATH -P "$PKG_CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security import $MAC_DEVELOPER_INSTALLER_CERT_PATH -P "$PKG_CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security set-key-partition-list -S apple-tool:,apple: -k "$PKG_KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

      # Package and sign for for the MacOS store (MACOS)
      - name: Package and sign for MacOS store
        if: runner.os == 'macOS'
        uses: ./.github/actions/macos-package
        with:
          app-cert-name: "3rd Party Mac Developer Application: William Bittle (W9HCQKU68J)"
          install-cert-name: "3rd Party Mac Developer Installer: William Bittle (W9HCQKU68J)"
          provisioning-profile: "${{ runner.temp }}/store/embedded.mobileprovision"
          architecture: "${{ matrix.arch }}"
          app-version: "${{ env.VERSION_NUMBER }}"
          pkg-suffix: "_store"
        
      # Package and sign for for MacOS adhoc deployment (MACOS)
      - name: Package and sign for MacOS adhoc deployment
        if: runner.os == 'macOS'
        uses: ./.github/actions/macos-package
        with:
          app-cert-name: "Developer ID Application: William Bittle (W9HCQKU68J)"
          install-cert-name: "Developer ID Installer: William Bittle (W9HCQKU68J)"
          provisioning-profile: "${{ runner.temp }}/adhoc/embedded.mobileprovision"
          architecture: "${{ matrix.arch }}"
          app-version: "${{ env.VERSION_NUMBER }}"
          pkg-suffix: "_adhoc"

      # Notarize the adhoc package (MACOS)
      - name: Notarize MacOS adhoc package
        if: runner.os == 'macOS'
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
        run: |
          PACKAGE="./target/Praisenter_${{ env.VERSION_NUMBER }}_${{ matrix.arch }}_adhoc.pkg"
          echo "Notarize package"
          xcrun notarytool submit "$PACKAGE" --apple-id "$APPLE_ID" --password "$APPLE_PASSWORD" --team-id "$APPLE_TEAM_ID" --output-format "json" --wait

          echo ""
          echo "<------------------------------------------------->"
          echo "Staple the package" 
          xcrun stapler staple "$PACKAGE"

          echo ""
          echo "<------------------------------------------------->"
          echo "Verify the pkg is install ready"
          spctl --assess --type install -v "$PACKAGE"

      # Publish the artifacts
      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          retention-days: 1
          path: |
            ./target/*.msi
            ./target/*.msixupload
            ./target/*.deb
            ./target/*.snap
            ./target/*.pkg

  github-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Get latest from the current branch
      - uses: actions/checkout@v2

      # This pulls the version number from the release-version.txt file
      - name: Read version
        id: readversion
        shell: pwsh
        run: |
          $content = Get-Content release-version.txt
          Write-Host "VERSION_NUMBER: $content"
          echo "VERSION_NUMBER=$content" >> $Env:GITHUB_ENV

      # Download all artifacts
      - name: Download artifacts
        uses: actions/download-artifact@v4

      # Create one release called 3.2.1 (for example)
      - name: Create Versioned Pre-Release
        uses: softprops/action-gh-release@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN}}"
          name: Praisenter v${{ env.VERSION_NUMBER }}.prerelease
          tag_name: ${{ env.VERSION_NUMBER }}.prerelease
          prerelease: false
          generate_release_notes: true
          make_latest: true
          files: | 
            ./dist-windows-latest/*.msi
            ./dist-windows-latest/*.msixupload
            ./dist-ubuntu-latest/*.deb
            ./dist-ubuntu-latest/*.snap
            ./dist-macos-15-intel/*.pkg
          # ./dist-macos-latest/*.pkg

#      # Now pull the latest release body
#      - name: Read release notes
#        id: release
#        uses: cardinalby/git-get-release-action@v1
#        env:
#          GITHUB_TOKEN: ${{ github.token }}
#        with:
#          tag: ${{ env.VERSION_NUMBER }}
#
#      # Now update the versioned release with the same body
#      - name: Copy release notes
#        uses: meeDamian/github-release@2.0
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          tag: ${{ env.VERSION_NUMBER }}
#          body: ${{ steps.release.outputs.body }}
#          allow_override: true

  # store-deploy:
  #   needs: github-release
  #   runs-on: ubuntu-latest
  #   steps:
  #     # Get latest from the current branch
  #     - uses: actions/checkout@v2

  #     # This pulls the version number from the release-version.txt file
  #     - name: Read version
  #       id: readversion
  #       shell: pwsh
  #       run: |
  #         $content = Get-Content release-version.txt
  #         Write-Host "VERSION_NUMBER: $content"
  #         echo "VERSION_NUMBER=$content" >> $Env:GITHUB_ENV

  #     # Download all artifacts
  #     - name: Download artifacts
  #       uses: actions/download-artifact@v4

  #     # now push to the stores