
# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build All

on:
  #  push:
  #    branches: [ main ]
  #  pull_request:
  #    branches: [ main ]
  workflow_dispatch:
    branches: [ master ]

# env:
#   DEV_IDENTITY: BXPZTQZ35S # Your Apple Dev identity, something like BXPZTQZ35S
#   PRIMARY_BUNDLE_ID: com.example.App # Unique to your app, often the launcher class

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-15-intel, macos-latest] # macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      # Get latest from the current branch
      - uses: actions/checkout@v4
        # with:
        #   lfs: true

      # List git LFS files
      - name: Create Git LFS file list
        run: git lfs ls-files -l |cut -d' ' -f1 |sort >.git/lfs-hashes.txt

      # Restore LFS files from cache
      - name: Restore Git LFS object cache
        uses: actions/cache@v4
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfsdata-v1-${{ hashFiles('.git/lfs-hashes.txt') }}
          restore-keys: |
            ${{ runner.os }}-lfsdata-v1-
            ${{ runner.os }}-lfsdata

      # Check latest LFS files
      - name: Fetch any needed Git LFS objects and prune extraneous ones
        run: git lfs fetch --prune

      # Get latest LFS files
      - name: Check out Git LFS content
        run: git lfs checkout

      # This pulls the version number from the release-version.txt file
      - name: Read version
        id: readversion
        shell: pwsh
        run: |
          $content = Get-Content release-version.txt
          Write-Host "VERSION_NUMBER: $content"
          echo "VERSION_NUMBER=$content" >> $Env:GITHUB_ENV
          
      # Add MSBuild (WINDOWS)
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        if: runner.os == 'Windows'

      # Install FFmpeg (UBUNTU)
      - name: Install FFmpeg
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libavcodec-dev libavformat-dev

      # Install Wix 6 (WINDOWS)
      # https://github.com/petr-panteleyev/jpackage-gradle-plugin/issues/38#issuecomment-2873402088
      - name: Install WiX 6
        run: |
          dotnet tool install --global wix --version 6.0.2
          wix extension add -g WixToolset.Util.wixext/6.0.2
          wix extension add -g WixToolset.Ui.wixext/6.0.2
        if: runner.os == 'Windows'

      # Setup Java w/ JavaFX
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'zulu'
          java-package: jdk+fx
          cache: 'maven'
      
      # Run the Maven Build
      - name: "Build with Maven"
        run: mvn -B clean install --file pom.xml

      # Now attempt to build the msix (WINDOWS)
      - name: "Set appxmanifest version number"
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $filePath = "./packaging/windows64/msix/Praisenter/Package.appxmanifest"
          $xml = [xml](Get-Content -Path $filePath)
          $xml.Package.Identity.Name = "${{ secrets.MSIX_IDENTITY_NAME }}"
          $xml.Package.Identity.Publisher = "${{ secrets.MSIX_IDENTITY_PUBLISHER }}"
          $xml.Package.Identity.Version = "${{ env.VERSION_NUMBER }}.0"
          $xml.Save($filePath)

      # Copy all the build artifacts to the /App folder (WINDOWS)
      - name: "Copy msi to msix location"
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path "./packaging/windows64/msix/Praisenter/App"
          $copied = Copy-Item -Path "./target/installer-work/image/Praisenter/*" -Destination "./packaging/windows64/msix/Praisenter/App" -Recurse -PassThru
          $copied | ForEach-Object {
            Write-Host "Copied: '$($_.FullName)'"
          }

      # Build the msixupload file (WINDOWS)
      - name: Build MSIX package
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Push-Location -Path ./packaging/windows64/msix/Praisenter
          MSBuild.exe /nologo /restore /p:AppxBundle=Never /p:UapAppxPackageBuildMode=StoreUpload  /p:Configuration=Release /p:Platform=x64 /p:AppxPackageDir=..\..\..\..\target\ /p:AppxPackageSigningEnabled=false
          Pop-Location

      # Copy deb to snap folder (UBUNTU)
      - name: Copy deb to snap folder
        if: runner.os == 'Linux'
        shell: pwsh
        run: |
          $source = "./target/praisenter_${{ env.VERSION_NUMBER }}_amd64.deb"
          $target = "./packaging/linux64/snap/praisenter.deb"
          Copy-Item $source $target
          Write-Host "Copied: '$source' to '$target'"

      # Update metainfo.xml (UBUNTU)
      - name: Set metainfo.xml version number
        if: runner.os == 'Linux'
        shell: pwsh
        run: |
          $filePath = "./packaging/linux64/snap/praisenter.metainfo.xml"
          $date = Get-Date -Format "yyyy-MM-dd"
          $xml = [xml](Get-Content -Path $filePath)
          $xml.component.releases.release.version = "${{ env.VERSION_NUMBER }}"
          $xml.component.releases.release.date = "$date"
          $xml.Save($filePath)

      # # Install snapcraft (UBUNTU)
      # - name: Install Snapcraft
      #   uses: samuelmeuli/action-snapcraft@v2
      - name: Build snap file
        if: runner.os == 'Linux'
        id: snapcraft
        uses: snapcore/action-build@v1
        with:
          path: ./packaging/linux64/snap/

      # Copy snap to target folder (UBUNTU)
      - name: Copy snap to target folder
        if: runner.os == 'Linux'
        shell: pwsh
        run: |
          $source = "${{ steps.snapcraft.outputs.snap }}"
          $target = "./target/praisenter_${{ env.VERSION_NUMBER }}_amd64.snap"
          Copy-Item $source $target
          Write-Host "Copied: '$source' to '$target'"

      # Rename the *.app with version+arch (MACOS)
	  - name: Rename MacOS app
        if: runner.os == 'Macos'
        shell: pwsh
        run: |
          $arch = "${{ runner.arch }}".ToLower()
          $source = "./target/Praisenter.app"
          $newName = "Praisenter_${{ env.VERSION_NUMBER }}_$arch.app"
          Rename-Item -Path $source -NewName $newName -ErrorAction Stop
          Write-Host "Renamed '$source' to '$newName'"
		  
      # Publish the artifacts
      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          retention-days: 1
          path: |
            ./target/*.msi
            ./target/*.msixupload
            ./target/*.deb
            ./target/*.snap
            ./target/*.app

  github-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Get latest from the current branch
      - uses: actions/checkout@v2

      # This pulls the version number from the release-version.txt file
      - name: Read version
        id: readversion
        shell: pwsh
        run: |
          $content = Get-Content release-version.txt
          Write-Host "VERSION_NUMBER: $content"
          echo "VERSION_NUMBER=$content" >> $Env:GITHUB_ENV

      # Download all artifacts
      - name: Download artifacts
        uses: actions/download-artifact@v4

#      # Now create the LATEST release
#      - name: Update Latest Release
#        uses: softprops/action-gh-release@v2
#        with:
#          token: "${{ secrets.GITHUB_TOKEN}}"
#          name: Praisenter Latest
#          tag_name: latest
#          prerelease: false
#          generate_release_notes: true
#          files: |
#            ./dist-windows-latest/*.msi
#            ./dist-windows-latest/*.msixupload
#            ./dist-ubuntu-latest/*.deb
#            ./dist-ubuntu-latest/*.snap
#            ./dist-macos-15-intel/*.app
#            ./dist-macos-latest/*.app

      # Create one release called 3.2.1 (for example)
      - name: Create Versioned Release
        uses: softprops/action-gh-release@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN}}"
          name: Praisenter v${{ env.VERSION_NUMBER }}
          tag_name: ${{ env.VERSION_NUMBER }}
          prerelease: false
          generate_release_notes: true
          make_latest: true
          files: | 
            ./dist-windows-latest/*.msi
            ./dist-windows-latest/*.msixupload
            ./dist-ubuntu-latest/*.deb
            ./dist-ubuntu-latest/*.snap
            ./dist-macos-15-intel/*.app
            ./dist-macos-latest/*.app

#      # Now pull the latest release body
#      - name: Read release notes
#        id: release
#        uses: cardinalby/git-get-release-action@v1
#        env:
#          GITHUB_TOKEN: ${{ github.token }}
#        with:
#          tag: ${{ env.VERSION_NUMBER }}
#
#      # Now update the versioned release with the same body
#      - name: Copy release notes
#        uses: meeDamian/github-release@2.0
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          tag: ${{ env.VERSION_NUMBER }}
#          body: ${{ steps.release.outputs.body }}
#          allow_override: true

  # store-deploy:
  #   needs: github-release
  #   runs-on: ubuntu-latest
  #   steps:
  #     # Get latest from the current branch
  #     - uses: actions/checkout@v2

  #     # This pulls the version number from the release-version.txt file
  #     - name: Read version
  #       id: readversion
  #       shell: pwsh
  #       run: |
  #         $content = Get-Content release-version.txt
  #         Write-Host "VERSION_NUMBER: $content"
  #         echo "VERSION_NUMBER=$content" >> $Env:GITHUB_ENV

  #     # Download all artifacts
  #     - name: Download artifacts
  #       uses: actions/download-artifact@v4

  #     # now push to the stores